### ISSUE TITLE
Why were I tagged?

### ISSUE THREAD

**Issue by madsmtm** [seanpm2001/seanpm2001#46]
Hey @seanpm2001, in https://github.com/seanpm2001/seanpm2001/issues/22 you've tagged me as helped this project out with "review", I think this is a mistake, I haven't seen this project before.

(Also, I find it a bit annoying to be tagged on something completely irrelevant to me, with zero context, which means I have to spend time trying to figure out if I'm just being stupid or if something else is going on...)

**Comment by seanpm2001** [comment]
I am sorry that it bugged you. I was creating a table of everyone I have interacted with on GitHub. The tag is related to communications on Ruffle-rs. I will not tag you any further.

**Comment by madsmtm** [comment]
Ah yeah, I thought I had seen your name before, just couldn't remember, thanks for clearing it up!

To your future work in #22: Having context is really important, I would have been much better off if you'd mentioned `ruffle-rs` from the beginning :wink:
