### ISSUE TITLE
Markdown links broken in others languages

### ISSUE THREAD

**Issue by Xwilarg** [seanpm2001/seanpm2001#8]
Hey,
Just opening an issue to tell you that the links in the translation of your README are all broken
Examples:
https://github.com/seanpm2001/seanpm2001/blob/master/.github/README_HMN.md
https://github.com/seanpm2001/seanpm2001/blob/master/.github/README_JA.md
https://github.com/seanpm2001/seanpm2001/blob/master/.github/README_HI.md

This is probably because when your translated everything, Google Translate added some spaces everywhere

Also this folder is called "Extermal": https://github.com/seanpm2001/seanpm2001/tree/master/Extermal
It looks like you wanted to write External but made a typo

**Comment by Xwilarg** [comment]
On a sidenote, you can change the language detected by your repository with a .gitattribute instead of creating files for that:
https://github.com/github/linguist/blob/master/docs/overrides.md

**Comment by seanpm2001** [comment]
Yes I am aware of this. I don't have the time or resources to fix it on my own. I don't know if the translations are even readable either. Google Translate does other weird things as well. For example, in German, for whatever reason `***` was changed to `***.` (added a dot in the end, so the markdown wouldn't render the divider line correctly)
I am also aware of the `Extermal` issue, I haven't gotten to fixing that yet, but I plan on it in the future.
Thank you for the advice. I will look into lingust overrides.

**Comment by seanpm2001** [comment]
I may not use linguistic overrides for a bit, as I have already become very invested with the separate linking, and platform compatibility (so that I can clone this repository to SourceForge, BitBucket, GitLab, etc. with compatibility errors) I am past halfway done, so I will try to see `.gitattributes` as a new option once I finish in a few days.
